[package]
name = "auto_migration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
systemstat = "0.1.11"
tokio = { version = "1.20.1", features = ["full"]}

